name: Supabase Inactive Fix
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Run
      id: run
      shell: bash
      env:
        CONFIG: ${{ secrets.CONFIG }}
        ENV: ${{ secrets.ENV }}
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        touch config.json
        echo "$CONFIG" >> config.json
        touch .env
        echo "$ENV" >> .env
        python main.py